source ~/.zshrc
export BUILD_MODE=$1
export UNIT_TEST=FALSE
export DIRECTORY=`pwd`
echo BUILD_MODE $BUILD_MODE UNIT_TEST $UNIT_TEST BUILD_PROFILE $ADA_APPLICATION_PROFILE ADA_OS_INCLUDE $ADA_OS_INCLUDE

./global_build.sh $BUILD_MODE $UNIT_TEST $ADA_APPLICATION_PROFILE $DIRECTORY

