# SlickEdit generated file.  Do not edit this file except in designated areas.

# Make command to use for dependencies
MAKE=make
RM=rm
MKDIR=mkdir

# -----Begin user-editable area-----

# -----End user-editable area-----

# If no configuration is specified, "Debug" will be used
ifndef CFG
CFG=Debug
endif

#
# Configuration: Debug
#
ifeq "$(CFG)" "Debug"
OUTDIR=Debug
OUTFILE=camera_test_driver
CFG_INC=
CFG_LIB=
CFG_OBJ=
COMMON_OBJ=$(OUTDIR)/camera_driver.o
OBJ=$(COMMON_OBJ) $(CFG_OBJ)
ALL_OBJ=$(OUTDIR)/camera_driver.o

COMPILE=gnat -c -g $(CFG_INC) -o "$(OUTDIR)/$(*F).o" "$<"
LINK=gnat -g -o "$(OUTFILE)" $(OBJ) $(CFG_LIB)
COMPILE_ADA=gnat -c -g -o "$(OUTDIR)/$(*F).o" "$<"
COMPILE_ADB=gnat -c -g -o "$(OUTDIR)/$(*F).o" "$<"

# Pattern rules
$(OUTDIR)/%.o : ../../applications/video/camera/driver/src/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../applications/video/camera/driver/src/%.adb
	$(COMPILE_ADB)

# Build rules
all: $(OUTFILE)

$(OUTFILE): $(OUTDIR) $(OBJ)
	$(LINK)

$(OUTDIR):
	$(MKDIR) -p "$(OUTDIR)"

# Rebuild this project
rebuild: cleanall
	@$(MAKE) -f "$(strip $(MAKEFILE_LIST))" $(MAKEFLAGS) all

# Clean this project
clean:
	$(RM) -f $(OUTFILE)
	$(RM) -f $(OBJ)

# Clean this project and all dependencies
cleanall: clean
endif

#
# Configuration: Release
#
ifeq "$(CFG)" "Release"
OUTDIR=Release
OUTFILE=camera_test_driver
CFG_INC=
CFG_LIB=
CFG_OBJ=
COMMON_OBJ=$(OUTDIR)/camera_driver.o
OBJ=$(COMMON_OBJ) $(CFG_OBJ)
ALL_OBJ=$(OUTDIR)/camera_driver.o

COMPILE=gnat -O -c $(CFG_INC) -o "$(OUTDIR)/$(*F).o" "$<"
LINK=gnat -O -o "$(OUTFILE)" $(OBJ) $(CFG_LIB)
COMPILE_ADA=gnat -O -c -o "$(OUTDIR)/$(*F).o" "$<"
COMPILE_ADB=gnat -O -c -o "$(OUTDIR)/$(*F).o" "$<"

# Pattern rules
$(OUTDIR)/%.o : ../../applications/video/camera/driver/src/%.ada
	$(COMPILE_ADA)

$(OUTDIR)/%.o : ../../applications/video/camera/driver/src/%.adb
	$(COMPILE_ADB)

# Build rules
all: $(OUTFILE)

$(OUTFILE): $(OUTDIR) $(OBJ)
	$(LINK)

$(OUTDIR):
	$(MKDIR) -p "$(OUTDIR)"

# Rebuild this project
rebuild: cleanall
	@$(MAKE) -f "$(strip $(MAKEFILE_LIST))" $(MAKEFLAGS) all

# Clean this project
clean:
	$(RM) -f $(OUTFILE)
	$(RM) -f $(OBJ)

# Clean this project and all dependencies
cleanall: clean
endif

#
# include dependencies:
#
